/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReverseImport } from './routes/reverse'
import { Route as GameImport } from './routes/game'
import { Route as CluesImport } from './routes/clues'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ReverseRoute = ReverseImport.update({
  id: '/reverse',
  path: '/reverse',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const CluesRoute = CluesImport.update({
  id: '/clues',
  path: '/clues',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/clues': {
      id: '/clues'
      path: '/clues'
      fullPath: '/clues'
      preLoaderRoute: typeof CluesImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/reverse': {
      id: '/reverse'
      path: '/reverse'
      fullPath: '/reverse'
      preLoaderRoute: typeof ReverseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clues': typeof CluesRoute
  '/game': typeof GameRoute
  '/reverse': typeof ReverseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clues': typeof CluesRoute
  '/game': typeof GameRoute
  '/reverse': typeof ReverseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clues': typeof CluesRoute
  '/game': typeof GameRoute
  '/reverse': typeof ReverseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/clues' | '/game' | '/reverse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/clues' | '/game' | '/reverse'
  id: '__root__' | '/' | '/about' | '/clues' | '/game' | '/reverse'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CluesRoute: typeof CluesRoute
  GameRoute: typeof GameRoute
  ReverseRoute: typeof ReverseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CluesRoute: CluesRoute,
  GameRoute: GameRoute,
  ReverseRoute: ReverseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/clues",
        "/game",
        "/reverse"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/clues": {
      "filePath": "clues.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/reverse": {
      "filePath": "reverse.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
