/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CluesImport } from './routes/clues'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ReverseLazyImport = createFileRoute('/reverse')()
const InfiniteLazyImport = createFileRoute('/infinite')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const ReverseLazyRoute = ReverseLazyImport.update({
  id: '/reverse',
  path: '/reverse',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/reverse.lazy').then((d) => d.Route))

const InfiniteLazyRoute = InfiniteLazyImport.update({
  id: '/infinite',
  path: '/infinite',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/infinite.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const CluesRoute = CluesImport.update({
  id: '/clues',
  path: '/clues',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clues': {
      id: '/clues'
      path: '/clues'
      fullPath: '/clues'
      preLoaderRoute: typeof CluesImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/infinite': {
      id: '/infinite'
      path: '/infinite'
      fullPath: '/infinite'
      preLoaderRoute: typeof InfiniteLazyImport
      parentRoute: typeof rootRoute
    }
    '/reverse': {
      id: '/reverse'
      path: '/reverse'
      fullPath: '/reverse'
      preLoaderRoute: typeof ReverseLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clues': typeof CluesRoute
  '/about': typeof AboutLazyRoute
  '/infinite': typeof InfiniteLazyRoute
  '/reverse': typeof ReverseLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clues': typeof CluesRoute
  '/about': typeof AboutLazyRoute
  '/infinite': typeof InfiniteLazyRoute
  '/reverse': typeof ReverseLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/clues': typeof CluesRoute
  '/about': typeof AboutLazyRoute
  '/infinite': typeof InfiniteLazyRoute
  '/reverse': typeof ReverseLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clues' | '/about' | '/infinite' | '/reverse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clues' | '/about' | '/infinite' | '/reverse'
  id: '__root__' | '/' | '/clues' | '/about' | '/infinite' | '/reverse'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CluesRoute: typeof CluesRoute
  AboutLazyRoute: typeof AboutLazyRoute
  InfiniteLazyRoute: typeof InfiniteLazyRoute
  ReverseLazyRoute: typeof ReverseLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CluesRoute: CluesRoute,
  AboutLazyRoute: AboutLazyRoute,
  InfiniteLazyRoute: InfiniteLazyRoute,
  ReverseLazyRoute: ReverseLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clues",
        "/about",
        "/infinite",
        "/reverse"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clues": {
      "filePath": "clues.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/infinite": {
      "filePath": "infinite.lazy.tsx"
    },
    "/reverse": {
      "filePath": "reverse.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
